---
version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for nuget
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "daily"
